name: cupertino_native_plus
description: Native Liquid Glass widgets for iOS and macOS with pixel-perfect fidelity.
version: 0.0.11
repository: https://github.com/NarekManukyan/cupertino_native_plus
issue_tracker: https://github.com/NarekManukyan/cupertino_native_plus/issues

topics:
  - ios
  - macos
  - cupertino
  - liquid-glass
  - native-widgets

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CupertinoNativePlugin
      macos:
        pluginClass: CupertinoNativePlugin
